### ISSUE TITLE
`openstack esi node list` errors out

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#253]

**Comment by tzumainn** [comment]
From --debug run:

RESP BODY: {"faultcode": "Server", "faultstring": "The request you have made requires authentication. (HTTP 401) (Request-ID: req-87fcb359-7384-4700-aee9-03499c49f237)", "debuginfo": null}
The request you have made requires authentication. (HTTP 401) (Request-ID: req-87fcb359-7384-4700-aee9-03499c49f237)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python3.6/site-packages/osc_lib/command/command.py", line 39, in run
    return super(Command, self).run(parsed_args)
  File "/usr/lib/python3.6/site-packages/cliff/display.py", line 115, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/local/lib/python3.6/site-packages/esileapclient/osc/v1/node.py", line 47, in take_action
    data = client.node.list(filters)
  File "/usr/local/lib/python3.6/site-packages/esileapclient/v1/node.py", line 64, in list
    nodes = self._list(url, os_esileap_api_version=os_esileap_api_version)
  File "/usr/local/lib/python3.6/site-packages/esileapclient/common/base.py", line 116, in _list
    raise exceptions.CommandError(json.loads(resp.text)['faultstring'])
osc_lib.exceptions.CommandError: The request you have made requires authentication. (HTTP 401) (Request-ID: req-87fcb359-7384-4700-aee9-03499c49f237)
clean_up ListNode: The request you have made requires authentication. (HTTP 401) (Request-ID: req-87fcb359-7384-4700-aee9-03499c49f237)

**Comment by tzumainn** [comment]
Turns out a bad keystone client was cached; opening an issue to potentially do one retry when that happens.
