### ISSUE TITLE
openstack esi node network list bug

### ISSUE THREAD

**Issue by tzumainn** [CCI-MOC/esi#279]
Sometimes, the following can happen if a node was detached from a network in an unideal way:

'NoneType' object has no attribute 'network_id'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/cliff/app.py", line 401, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python3.6/site-packages/osc_lib/command/command.py", line 39, in run
    return super(Command, self).run(parsed_args)
  File "/usr/lib/python3.6/site-packages/cliff/display.py", line 115, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/local/lib/python3.6/site-packages/esiclient/v1/node_network.py", line 82, in take_action
    network_id = neutron_port.network_id

**Comment by tzumainn** [comment]
Happens if an ironic node retains its VIF after the node is detached from the network
